#!/usr/bin/env bash

printf "\033[0;34mValidating conventional commit messages... \033[0m\n"

commit_msg_type_regex='feat|fix|refactor|style|test|docs|build|chore|ops'
commit_msg_scope_regex='.{1,20}'
commit_msg_subject_regex='.{1,100}'
commit_msg_regex="^(${commit_msg_type_regex})(\(${commit_msg_scope_regex}\))?: (${commit_msg_subject_regex})\$"
merge_msg_regex="^Merge branch '.+'\$"
revert_msg_regex="^Revert \".+\"\$"
msg="^(\[maven-release-plugin\].*)$|$commit_msg_regex"
if ! [[ $(cat "$1") =~ $msg ]]; then
  cat "$1" >&2
  printf "\033[0;31mERROR: ERROR: Invalid commit message format ❌" >&2
  cat "$1" >&2
  printf "\033[0;32mFor more details: https://www.conventionalcommits.org/pt-br/v1.0.0/\033[0\n"
  exit 1
fi
  printf  "\033[0;32mValid commit message ✅\033[0m\n"