#!/usr/bin/env bash

printf "\033[0;34mRunning linters:\n"


if ! mvn spotless:check; then
  printf '\033[0;31mVerificações de Qualidade e Testes falharam. Checar os logs acima para resolver as falhas\n'
  exit 1
fi

printf "\033[0;32mCommit verificado com sucesso!\n"





